[package]
name = "weirdo"
version = "0.1.0"
authors = ["Artur Ciesielski <artur.ciesielski@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
log = "0.4"
serde = { version = "1.0", features = ["derive"]}
toml = "0.5"
